### ISSUE TITLE
Мелкие косяки

### ISSUE THREAD

**Issue by JoCat** [GravitLauncher/QuasarWiki#1]
Раздел [Настройка хостинга](https://launcher.gravit.pro/install#hostconfigure)

Вкладка Debian
зачем ставить curl, когда используется wget?
с учётом того что дальше в вики используется curl не лучше ли тогда все запросы сделать curl-ом

![image](https://user-images.githubusercontent.com/13483132/137169974-a54f9387-f626-4fe2-a166-34cd0ff8e462.png)

Также для установки указан пакет nftables, но дальше он нигде не используется
![image](https://user-images.githubusercontent.com/13483132/137170403-788f54d2-8885-4aca-a85e-e36e7b57f964.png)

**Comment by microwin7** [comment]
![image](https://user-images.githubusercontent.com/12544425/137174441-2e8a63c1-d5ab-4340-ac7f-15dfca90292c.png)
Где мой рантайм?
![image](https://user-images.githubusercontent.com/12544425/137174478-93aa7117-6062-4b9e-a246-fc1ecdad21ab.png)
Даже этого не создалось в папке
![image](https://user-images.githubusercontent.com/12544425/137174502-d24f30b1-eb82-458d-bbdb-c11458ee60ea.png)

**Comment by microwin7** [comment]
> > ![image](https://user-images.githubusercontent.com/12544425/137174441-2e8a63c1-d5ab-4340-ac7f-15dfca90292c.png) Где мой рантайм? ![image](https://user-images.githubusercontent.com/12544425/137174478-93aa7117-6062-4b9e-a246-fc1ecdad21ab.png) Даже этого не создалось в папке ![image](https://user-images.githubusercontent.com/12544425/137174502-d24f30b1-eb82-458d-bbdb-c11458ee60ea.png)
> 
> Это скорее в ишью лаунчера надо

Одно исходящее из второго, если не в лаунчере, то на Вики всё должно быть

**Comment by gravit0** [comment]
Исправила https://github.com/GravitLauncher/QuasarWiki/commit/118a558ce346d40fd86907b0b9cea3573c00040c

**Comment by JoCat** [comment]
@microwin7 Пересоздай ишью с тем что не пофиксили от тебя (один фикс - одна ишью) 😏
